### ISSUE TITLE
Open3 for shell commands

### ISSUE THREAD

**Issue by jsm13** [ga-dc/installfest#67]
Currently using backticks for shell commands and [piping stdError to stdOut with `2>&1`](https://github.com/ga-dc/installfest/blob/559dc5d924628465b700a7f15f7ee1db9d7079dc/Rakefile#L71); I think it may be better to use [Open3](https://docs.ruby-lang.org/en/2.0.0/Open3.html) as described in [this blog post](http://blog.honeybadger.io/capturing-stdout-stderr-from-shell-commands-via-ruby/)

**Comment by superbuggy** [comment]
Open3 does something like organizing stdout/stderr into Hashes and improve the maintainability of installfest.
